// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertGameEvent = `-- name: InsertGameEvent :exec
INSERT INTO game_events (room_id, user_id, event_type, target_id, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertGameEventParams struct {
	RoomID    int64          `json:"room_id"`
	UserID    int64          `json:"user_id"`
	EventType string         `json:"event_type"`
	TargetID  sql.NullInt64  `json:"target_id"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt int64          `json:"created_at"`
}

func (q *Queries) InsertGameEvent(ctx context.Context, arg InsertGameEventParams) error {
	_, err := q.db.ExecContext(ctx, insertGameEvent,
		arg.RoomID,
		arg.UserID,
		arg.EventType,
		arg.TargetID,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const setAccusedIfAllowed = `-- name: SetAccusedIfAllowed :exec
UPDATE games
SET accused_id = ?
WHERE games.room_id = ?
  AND games.paused = 1
  AND games.paused_id = ?
  AND EXISTS (
    SELECT 1
    FROM room_members AS rm
    WHERE rm.room_id = games.room_id
      AND rm.user_id = ?
  )
`

type SetAccusedIfAllowedParams struct {
	AccusedID sql.NullInt64 `json:"accused_id"`
	RoomID    int64         `json:"room_id"`
	PausedID  sql.NullInt64 `json:"paused_id"`
	UserID    int64         `json:"user_id"`
}

func (q *Queries) SetAccusedIfAllowed(ctx context.Context, arg SetAccusedIfAllowedParams) error {
	_, err := q.db.ExecContext(ctx, setAccusedIfAllowed,
		arg.AccusedID,
		arg.RoomID,
		arg.PausedID,
		arg.UserID,
	)
	return err
}

const upsertGameForRoom = `-- name: UpsertGameForRoom :exec
INSERT INTO games (room_id, spy_id, location, paused, timer_duration, started_at)
VALUES (?, ?, ?, 0, ?, unixepoch())
ON CONFLICT(room_id) DO UPDATE SET
    spy_id = excluded.spy_id,
    location = excluded.location,
    paused = excluded.paused,
    timer_remaining = excluded.timer_remaining,
    started_at = excluded.started_at
`

type UpsertGameForRoomParams struct {
	RoomID        int64  `json:"room_id"`
	SpyID         int64  `json:"spy_id"`
	Location      string `json:"location"`
	TimerDuration int64  `json:"timer_duration"`
}

func (q *Queries) UpsertGameForRoom(ctx context.Context, arg UpsertGameForRoomParams) error {
	_, err := q.db.ExecContext(ctx, upsertGameForRoom,
		arg.RoomID,
		arg.SpyID,
		arg.Location,
		arg.TimerDuration,
	)
	return err
}
