// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Game struct {
	ID            int64  `json:"id"`
	RoomID        int64  `json:"room_id"`
	SpyID         int64  `json:"spy_id"`
	Location      string `json:"location"`
	LocationPool  string `json:"location_pool"`
	StartedAt     int64  `json:"started_at"`
	TimerDuration int64  `json:"timer_duration"`
}

type GameEvent struct {
	ID        int64          `json:"id"`
	GameID    int64          `json:"game_id"`
	UserID    int64          `json:"user_id"`
	EventType string         `json:"event_type"`
	TargetID  sql.NullInt64  `json:"target_id"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt int64          `json:"created_at"`
}

type Room struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Code          string `json:"code"`
	HostID        int64  `json:"host_id"`
	MaxLocations  int64  `json:"max_locations"`
	MaxPlayers    int64  `json:"max_players"`
	CreatedAt     int64  `json:"created_at"`
	State         string `json:"state"`
	TimerDuration int64  `json:"timer_duration"`
}

type RoomMember struct {
	RoomID   int64 `json:"room_id"`
	UserID   int64 `json:"user_id"`
	JoinedAt int64 `json:"joined_at"`
	IsReady  int64 `json:"is_ready"`
	Points   int64 `json:"points"`
}

type User struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	CreatedAt    int64  `json:"created_at"`
	CrabAvatar   string `json:"crab_avatar"`
}
