// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Room struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	HostID     int64  `json:"host_id"`
	MaxPlayers int64  `json:"max_players"`
	Status     string `json:"status"`
	IsPrivate  int64  `json:"is_private"`
	CreatedAt  int64  `json:"created_at"`
}

type RoomMember struct {
	RoomID   int64         `json:"room_id"`
	UserID   int64         `json:"user_id"`
	JoinedAt int64         `json:"joined_at"`
	IsReady  int64         `json:"is_ready"`
	Team     sql.NullInt64 `json:"team"`
}

type User struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	CreatedAt   int64  `json:"created_at"`
}
