// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlcgen

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, host_id, max_players, max_locations)
VALUES (?, ?, ?, ?)
RETURNING id, name, host_id, max_locations, max_players, status, is_private, created_at
`

type CreateRoomParams struct {
	Name         string `json:"name"`
	HostID       int64  `json:"host_id"`
	MaxPlayers   int64  `json:"max_players"`
	MaxLocations int64  `json:"max_locations"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.Name,
		arg.HostID,
		arg.MaxPlayers,
		arg.MaxLocations,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostID,
		&i.MaxLocations,
		&i.MaxPlayers,
		&i.Status,
		&i.IsPrivate,
		&i.CreatedAt,
	)
	return i, err
}

const getAllRooms = `-- name: GetAllRooms :many
SELECT id, name, host_id, max_locations, max_players, status, is_private, created_at FROM rooms
`

func (q *Queries) GetAllRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getAllRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HostID,
			&i.MaxLocations,
			&i.MaxPlayers,
			&i.Status,
			&i.IsPrivate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
