// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlcgen

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, host_id, max_players, max_locations, code, timer_duration)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, code, host_id, max_locations, max_players, created_at, state, timer_duration
`

type CreateRoomParams struct {
	Name          string `json:"name"`
	HostID        int64  `json:"host_id"`
	MaxPlayers    int64  `json:"max_players"`
	MaxLocations  int64  `json:"max_locations"`
	Code          string `json:"code"`
	TimerDuration int64  `json:"timer_duration"`
}

// -------------------------
// CREATE, UPDATE, DELETE
// -------------------------
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.Name,
		arg.HostID,
		arg.MaxPlayers,
		arg.MaxLocations,
		arg.Code,
		arg.TimerDuration,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HostID,
		&i.MaxLocations,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.State,
		&i.TimerDuration,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = ?
`

func (q *Queries) DeleteRoom(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getAllRooms = `-- name: GetAllRooms :many
SELECT id, name, code, host_id, max_locations, max_players, created_at, state, timer_duration FROM rooms
`

func (q *Queries) GetAllRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getAllRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.HostID,
			&i.MaxLocations,
			&i.MaxPlayers,
			&i.CreatedAt,
			&i.State,
			&i.TimerDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameByRoomID = `-- name: GetGameByRoomID :one
SELECT room_id, spy_id, location, paused, started_at, timer_remaining FROM games WHERE room_id = ?
`

func (q *Queries) GetGameByRoomID(ctx context.Context, roomID int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByRoomID, roomID)
	var i Game
	err := row.Scan(
		&i.RoomID,
		&i.SpyID,
		&i.Location,
		&i.Paused,
		&i.StartedAt,
		&i.TimerRemaining,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, name, code, host_id, max_locations, max_players, created_at, state, timer_duration FROM rooms WHERE code = ?
`

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByCode, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HostID,
		&i.MaxLocations,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.State,
		&i.TimerDuration,
	)
	return i, err
}

const getRoomById = `-- name: GetRoomById :one
SELECT id, name, code, host_id, max_locations, max_players, created_at, state, timer_duration FROM rooms WHERE id = ?
`

func (q *Queries) GetRoomById(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomById, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HostID,
		&i.MaxLocations,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.State,
		&i.TimerDuration,
	)
	return i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT users.id, users.username, users.display_name, users.crab_avatar, rm.is_ready
FROM room_members rm
JOIN users ON users.id = rm.user_id
WHERE rm.room_id = ?
`

type GetRoomMembersRow struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	CrabAvatar  string `json:"crab_avatar"`
	IsReady     int64  `json:"is_ready"`
}

func (q *Queries) GetRoomMembers(ctx context.Context, roomID int64) ([]GetRoomMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomMembersRow{}
	for rows.Next() {
		var i GetRoomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.CrabAvatar,
			&i.IsReady,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsAndMembers = `-- name: GetRoomsAndMembers :many
SELECT rooms.id, rooms.name, rooms.code, rooms.host_id, rooms.max_locations, rooms.max_players, rooms.created_at, rooms.state, rooms.timer_duration, COUNT(rm.user_id) AS player_count
FROM rooms
LEFT JOIN room_members AS rm ON rm.room_id = rooms.id
GROUP BY rooms.id
`

type GetRoomsAndMembersRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Code          string `json:"code"`
	HostID        int64  `json:"host_id"`
	MaxLocations  int64  `json:"max_locations"`
	MaxPlayers    int64  `json:"max_players"`
	CreatedAt     int64  `json:"created_at"`
	State         string `json:"state"`
	TimerDuration int64  `json:"timer_duration"`
	PlayerCount   int64  `json:"player_count"`
}

func (q *Queries) GetRoomsAndMembers(ctx context.Context) ([]GetRoomsAndMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsAndMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomsAndMembersRow{}
	for rows.Next() {
		var i GetRoomsAndMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.HostID,
			&i.MaxLocations,
			&i.MaxPlayers,
			&i.CreatedAt,
			&i.State,
			&i.TimerDuration,
			&i.PlayerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinRoom = `-- name: JoinRoom :exec
INSERT OR IGNORE INTO room_members (room_id, user_id) VALUES (?, ?)
`

type JoinRoomParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) error {
	_, err := q.db.ExecContext(ctx, joinRoom, arg.RoomID, arg.UserID)
	return err
}

const leaveRoom = `-- name: LeaveRoom :exec
DELETE FROM room_members WHERE room_id = ? AND user_id = ?
`

type LeaveRoomParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) error {
	_, err := q.db.ExecContext(ctx, leaveRoom, arg.RoomID, arg.UserID)
	return err
}

const togglePauseGame = `-- name: TogglePauseGame :exec
UPDATE games 
SET paused = 1 - paused 
WHERE room_id = ?
RETURNING room_id, spy_id, location, paused, started_at, timer_remaining
`

func (q *Queries) TogglePauseGame(ctx context.Context, roomID int64) error {
	_, err := q.db.ExecContext(ctx, togglePauseGame, roomID)
	return err
}

const updateGameTimer = `-- name: UpdateGameTimer :exec
UPDATE games
SET timer_remaining = ?
WHERE room_id = ?
`

type UpdateGameTimerParams struct {
	TimerRemaining int64 `json:"timer_remaining"`
	RoomID         int64 `json:"room_id"`
}

func (q *Queries) UpdateGameTimer(ctx context.Context, arg UpdateGameTimerParams) error {
	_, err := q.db.ExecContext(ctx, updateGameTimer, arg.TimerRemaining, arg.RoomID)
	return err
}

const updateRoomHost = `-- name: UpdateRoomHost :exec
UPDATE rooms SET host_id = ? WHERE id = ?
`

type UpdateRoomHostParams struct {
	HostID int64 `json:"host_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateRoomHost(ctx context.Context, arg UpdateRoomHostParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomHost, arg.HostID, arg.ID)
	return err
}

const updateRoomState = `-- name: UpdateRoomState :exec
UPDATE rooms SET state = ? WHERE id = ?
`

type UpdateRoomStateParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateRoomState(ctx context.Context, arg UpdateRoomStateParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomState, arg.State, arg.ID)
	return err
}

const upsertGameForRoom = `-- name: UpsertGameForRoom :exec
INSERT INTO games (room_id, spy_id, location, paused, timer_remaining, started_at)
VALUES (?, ?, ?, 0, ?, unixepoch())
ON CONFLICT(room_id) DO UPDATE SET
    spy_id = excluded.spy_id,
    location = excluded.location,
    paused = excluded.paused,
    timer_remaining = excluded.timer_remaining,
    started_at = excluded.started_at
`

type UpsertGameForRoomParams struct {
	RoomID         int64  `json:"room_id"`
	SpyID          int64  `json:"spy_id"`
	Location       string `json:"location"`
	TimerRemaining int64  `json:"timer_remaining"`
}

func (q *Queries) UpsertGameForRoom(ctx context.Context, arg UpsertGameForRoomParams) error {
	_, err := q.db.ExecContext(ctx, upsertGameForRoom,
		arg.RoomID,
		arg.SpyID,
		arg.Location,
		arg.TimerRemaining,
	)
	return err
}
