// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlcgen

import (
	"context"
)

const addPointsToAllExcept = `-- name: AddPointsToAllExcept :exec
UPDATE room_members SET points = points + ? WHERE room_id = ? AND user_id != ?
`

type AddPointsToAllExceptParams struct {
	Points int64 `json:"points"`
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddPointsToAllExcept(ctx context.Context, arg AddPointsToAllExceptParams) error {
	_, err := q.db.ExecContext(ctx, addPointsToAllExcept, arg.Points, arg.RoomID, arg.UserID)
	return err
}

const addPointsToMember = `-- name: AddPointsToMember :exec
UPDATE room_members SET points = points + ? WHERE room_id = ? AND user_id = ?
`

type AddPointsToMemberParams struct {
	Points int64 `json:"points"`
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddPointsToMember(ctx context.Context, arg AddPointsToMemberParams) error {
	_, err := q.db.ExecContext(ctx, addPointsToMember, arg.Points, arg.RoomID, arg.UserID)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, host_id, max_players, max_locations, code, timer_duration)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, code, host_id, max_locations, max_players, created_at, state, timer_duration
`

type CreateRoomParams struct {
	Name          string `json:"name"`
	HostID        int64  `json:"host_id"`
	MaxPlayers    int64  `json:"max_players"`
	MaxLocations  int64  `json:"max_locations"`
	Code          string `json:"code"`
	TimerDuration int64  `json:"timer_duration"`
}

// -------------------------
// CREATE, UPDATE, DELETE
// -------------------------
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.Name,
		arg.HostID,
		arg.MaxPlayers,
		arg.MaxLocations,
		arg.Code,
		arg.TimerDuration,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HostID,
		&i.MaxLocations,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.State,
		&i.TimerDuration,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, name, code, host_id, max_locations, max_players, created_at, state, timer_duration FROM rooms WHERE code = ?
`

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByCode, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HostID,
		&i.MaxLocations,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.State,
		&i.TimerDuration,
	)
	return i, err
}

const getRoomById = `-- name: GetRoomById :one
SELECT id, name, code, host_id, max_locations, max_players, created_at, state, timer_duration FROM rooms WHERE id = ?
`

func (q *Queries) GetRoomById(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomById, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HostID,
		&i.MaxLocations,
		&i.MaxPlayers,
		&i.CreatedAt,
		&i.State,
		&i.TimerDuration,
	)
	return i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT room_id, user_id, joined_at, is_ready, points, id, username, password_hash, display_name, created_at, crab_avatar
FROM room_members rm
JOIN users ON users.id = rm.user_id
WHERE rm.room_id = ?
`

type GetRoomMembersRow struct {
	RoomID       int64  `json:"room_id"`
	UserID       int64  `json:"user_id"`
	JoinedAt     int64  `json:"joined_at"`
	IsReady      int64  `json:"is_ready"`
	Points       int64  `json:"points"`
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	CreatedAt    int64  `json:"created_at"`
	CrabAvatar   string `json:"crab_avatar"`
}

func (q *Queries) GetRoomMembers(ctx context.Context, roomID int64) ([]GetRoomMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomMembersRow{}
	for rows.Next() {
		var i GetRoomMembersRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.JoinedAt,
			&i.IsReady,
			&i.Points,
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.CreatedAt,
			&i.CrabAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinRoom = `-- name: JoinRoom :exec
INSERT OR IGNORE INTO room_members (room_id, user_id) VALUES (?, ?)
`

type JoinRoomParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) error {
	_, err := q.db.ExecContext(ctx, joinRoom, arg.RoomID, arg.UserID)
	return err
}

const leaveRoom = `-- name: LeaveRoom :exec
DELETE FROM room_members WHERE room_id = ? AND user_id = ?
`

type LeaveRoomParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) error {
	_, err := q.db.ExecContext(ctx, leaveRoom, arg.RoomID, arg.UserID)
	return err
}

const updateRoomHost = `-- name: UpdateRoomHost :exec
UPDATE rooms SET host_id = ? WHERE id = ?
`

type UpdateRoomHostParams struct {
	HostID int64 `json:"host_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateRoomHost(ctx context.Context, arg UpdateRoomHostParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomHost, arg.HostID, arg.ID)
	return err
}

const updateRoomState = `-- name: UpdateRoomState :exec
UPDATE rooms SET state = ? WHERE id = ?
`

type UpdateRoomStateParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateRoomState(ctx context.Context, arg UpdateRoomStateParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomState, arg.State, arg.ID)
	return err
}
